version: '3.8'


services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./frontend/.env
      
    ports:
      - "3001:80"
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod

    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    ports:
      - "8081:8080"

  postgres:
    image: postgres:alpine
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=mysupersecretpassword
    healthcheck:                      
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  postgres_data: