FROM oven/bun:1 

WORKDIR /backend    

COPY package.json bun.lock ./

RUN bun install 

COPY . .

RUN apt-get update -y && apt-get install -y openssl

RUN cd ./prisma && bunx prisma generate

EXPOSE 5555

EXPOSE 8080

CMD ["sh", "-c", "bunx prisma migrate deploy && bun run start"]

